portal:
  build: .
  env_file:
    - .chameleon_env
  volumes:
    - ../logs/nginx_access_chameleoncloud.log:/var/log/nginx/access_chameleoncloud.log
    - ../logs/nginx_error_chameleoncloud.log:/var/log/nginx/error_chameleoncloud.log
    - ../logs/django_chameleon_auth.log:/tmp/chameleon_auth.log
    - ../logs/django_chameleon.log:/tmp/chameleon.log
    - ../certs/certs0:/etc/ssl/chameleoncloud.org
    - ../certs/certs1:/etc/ssl/www.chameleon.tacc.utexas.edu
    - ../certs/certs2:/etc/ssl/api.chameleoncloud.org
    - ../media:/project/media
    - .:/project
  ports:
    - 80:80
    - 443:443
  links:
    - referenceapi:referenceapi
referenceapi:
  image: referenceapi:latest
  ports:
    - 8000:8000
