portal:
  build: .
  env_file:
    - .chameleon_env
  volumes:
    - ../logs/nginx_access_chameleoncloud.log:/var/log/nginx/access_chameleoncloud.log
    - ../logs/nginx_error_chameleoncloud.log:/var/log/nginx/error_chameleoncloud.log
    - ../logs/django_chameleon_auth.log:/tmp/chameleon_auth.log
    - ../logs/django_chameleon.log:/tmp/chameleon.log
    - ../media:/project/media
    - .:/project
  ports:
    - 8888:8888
  links:
    - referenceapi:referenceapi
  command: python manage.py runserver 0.0.0.0:8888
referenceapi:
  image: referenceapi:latest
  ports:
    - 8000:8000
