portal:
  build: .
  env_file:
    - .chameleon_env
  volumes:
    - ../logs/django:/var/log/django
    - ../logs/nginx:/var/log/nginx
    - ../media:/project/media
    - .:/project
  ports:
    - 8888:8888
  links:
    - referenceapi:referenceapi
  command: python manage.py runserver 0.0.0.0:8888
referenceapi:
  image: referenceapi:latest
  ports:
    - 8000:8000
